
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETE_CENTRAR = 36;
  public static final int CORCHETE_VIDEO = 32;
  public static final int INICIO_ATRIBUTO_PADRE = 47;
  public static final int FIN_PARAMETRO = 14;
  public static final int CORCHETE_IMAGEN = 31;
  public static final int CORCHETE_JUSTIFICAR = 37;
  public static final int INICIO_ATRIBUTO_ETIQUETAS = 48;
  public static final int FIN_ACCIONES = 12;
  public static final int INICIO_PARAMETRO_FECHA_MODIFICACION = 17;
  public static final int INICIO_ATRIBUTO_ALTURA = 45;
  public static final int INICIO_ATRIBUTOS = 50;
  public static final int INICIO_MODIFICAR_COMPONENTE = 9;
  public static final int INICIO_ATRIBUTO_COLOR = 43;
  public static final int INICIO_PARAMETRO_ID = 13;
  public static final int INICIO_PARAMETROS = 24;
  public static final int INICIO_PARAMETRO_USUARIO_CREACION = 15;
  public static final int INICIO_ETIQUETA_ID = 26;
  public static final int INICIO_BORRAR_COMPONENTE = 8;
  public static final int CORCHETE_MENU = 33;
  public static final int INICIO_AGREGAR_COMPONENTE = 7;
  public static final int FIN_ETIQUETAS = 28;
  public static final int CORCHETE_DERECHA = 34;
  public static final int INICIO_PARAMETRO_PADRE = 20;
  public static final int CORCHETE_ID = 40;
  public static final int CORCHETE_PARRAFO = 30;
  public static final int INICIO_NUEVO_SITIO_WEB = 2;
  public static final int INICIO_PARAMETRO_PAGINA = 22;
  public static final int INICIO_ACCIONES = 11;
  public static final int EOF = 0;
  public static final int INICIO_ATRIBUTO_ALINEACION = 42;
  public static final int INICIO_BORRAR_PAGINA = 5;
  public static final int INICIO_PARAMETRO_CLASE = 23;
  public static final int INICIO_ATRIBUTO_TEXTO = 41;
  public static final int INICIO_PARAMETRO_FECHA_CREACION = 16;
  public static final int error = 1;
  public static final int INICIO_NUEVA_PAGINA = 4;
  public static final int CORCHETE_IZQUIERDA = 35;
  public static final int CORCHETE_ETIQUETAS = 52;
  public static final int INICIO_BORRAR_SITIO_WEB = 3;
  public static final int FIN_ACCION = 10;
  public static final int CORCHETE_TITULO = 29;
  public static final int INICIO_ATRIBUTO_ANCHO = 46;
  public static final int INICIO_PARAMETRO_TITULO = 19;
  public static final int FIN_ATRIBUTOS = 51;
  public static final int FIN_PARAMETROS = 25;
  public static final int CORCHETE_NUMEROS = 39;
  public static final int INICIO_ETIQUETAS = 27;
  public static final int INICIO_PARAMETRO_SITIO = 21;
  public static final int FIN_ATRIBUTO = 49;
  public static final int CORCHETE_HEXADECIMAL = 38;
  public static final int INICIO_MODIFICAR_PAGINA = 6;
  public static final int INICIO_ATRIBUTO_ORIGEN = 44;
  public static final int INICIO_PARAMETRO_USUARIO_MODIFICACION = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO_NUEVO_SITIO_WEB",
  "INICIO_BORRAR_SITIO_WEB",
  "INICIO_NUEVA_PAGINA",
  "INICIO_BORRAR_PAGINA",
  "INICIO_MODIFICAR_PAGINA",
  "INICIO_AGREGAR_COMPONENTE",
  "INICIO_BORRAR_COMPONENTE",
  "INICIO_MODIFICAR_COMPONENTE",
  "FIN_ACCION",
  "INICIO_ACCIONES",
  "FIN_ACCIONES",
  "INICIO_PARAMETRO_ID",
  "FIN_PARAMETRO",
  "INICIO_PARAMETRO_USUARIO_CREACION",
  "INICIO_PARAMETRO_FECHA_CREACION",
  "INICIO_PARAMETRO_FECHA_MODIFICACION",
  "INICIO_PARAMETRO_USUARIO_MODIFICACION",
  "INICIO_PARAMETRO_TITULO",
  "INICIO_PARAMETRO_PADRE",
  "INICIO_PARAMETRO_SITIO",
  "INICIO_PARAMETRO_PAGINA",
  "INICIO_PARAMETRO_CLASE",
  "INICIO_PARAMETROS",
  "FIN_PARAMETROS",
  "INICIO_ETIQUETA_ID",
  "INICIO_ETIQUETAS",
  "FIN_ETIQUETAS",
  "CORCHETE_TITULO",
  "CORCHETE_PARRAFO",
  "CORCHETE_IMAGEN",
  "CORCHETE_VIDEO",
  "CORCHETE_MENU",
  "CORCHETE_DERECHA",
  "CORCHETE_IZQUIERDA",
  "CORCHETE_CENTRAR",
  "CORCHETE_JUSTIFICAR",
  "CORCHETE_HEXADECIMAL",
  "CORCHETE_NUMEROS",
  "CORCHETE_ID",
  "INICIO_ATRIBUTO_TEXTO",
  "INICIO_ATRIBUTO_ALINEACION",
  "INICIO_ATRIBUTO_COLOR",
  "INICIO_ATRIBUTO_ORIGEN",
  "INICIO_ATRIBUTO_ALTURA",
  "INICIO_ATRIBUTO_ANCHO",
  "INICIO_ATRIBUTO_PADRE",
  "INICIO_ATRIBUTO_ETIQUETAS",
  "FIN_ATRIBUTO",
  "INICIO_ATRIBUTOS",
  "FIN_ATRIBUTOS",
  "CORCHETE_ETIQUETAS"
  };
}

