
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int CONTRASENA = 7;
  public static final int IDD = 8;
  public static final int ANGULAR_CERRADO = 3;
  public static final int USUARIO = 6;
  public static final int EOF = 0;
  public static final int CORCHETE_CERRADO = 10;
  public static final int ANGULAR_ABIERTO = 2;
  public static final int DIAGONAL = 4;
  public static final int error = 1;
  public static final int CORCHETE_ABIERTO = 9;
  public static final int NOMBRE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ANGULAR_ABIERTO",
  "ANGULAR_CERRADO",
  "DIAGONAL",
  "NOMBRE",
  "USUARIO",
  "CONTRASENA",
  "IDD",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO"
  };
}

