
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym3 {
  /* terminals */
  public static final int FIN_MENSAJE = 5;
  public static final int IDD = 8;
  public static final int INICIO_MENSAJE = 4;
  public static final int EOF = 0;
  public static final int INICIO_ERROR = 2;
  public static final int CORCHETE_CERRADO = 7;
  public static final int error = 1;
  public static final int CORCHETE_ABIERTO = 6;
  public static final int FIN_ERROR = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO_ERROR",
  "FIN_ERROR",
  "INICIO_MENSAJE",
  "FIN_MENSAJE",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "IDD"
  };
}

